owner: tdulcet # timvisee
repo: send-instances-status

sites:
  - name: send.vis.ee
    url: https://send.vis.ee
    assignees:
      - timvisee
  - name: send.mni.li
    url: https://send.mni.li
  - name: send.monks.tools
    url: https://send.monks.tools
  - name: send.boblorange.net
    url: https://send.boblorange.net
  - name: send.aurorabilisim.com
    url: https://send.aurorabilisim.com
  - name: send.artemislena.eu
    url: https://send.artemislena.eu
  - name: fileupload.ggc-project.de
    url: https://fileupload.ggc-project.de
  - name: drop.chapril.org
    url: https://drop.chapril.org
  - name: send.jeugdhulp.be
    url: https://send.jeugdhulp.be
  - name: files.psu.ru
    url: https://files.psu.ru
  - name: send.datenpost.app
    url: https://send.datenpost.app
  - name: s.opnxng.com
    url: https://s.opnxng.com
  - name: send.cyberjake.xyz
    url: https://send.cyberjake.xyz
  - name: send.kokomo.cloud
    url: https://send.kokomo.cloud
  - name: send.adminforge.de
    url: https://send.adminforge.de
  - name: send.turingpoint.de
    url: https://send.turingpoint.de
  - name: send.aslaets.be
    url: https://send.aslaets.be
  - name: send.codespace.cz
    url: https://send.codespace.cz
  - name: upload.nolog.cz
    url: https://upload.nolog.cz
  - name: ch.skysend.ch
    url: https://ch.skysend.ch
  - name: de.skysend.ch
    url: https://de.skysend.ch
  - name: allthefiles.net
    url: https://allthefiles.net
  - name: send.canine.tools
    url: https://send.canine.tools
  - name: secureshar.ing
    url: https://secureshar.ing
  - name: send.aezafiles.net
    url: https://send.aezafiles.net
  - name: send.sdad.pro
    url: https://send.sdad.pro
  - name: send.skylerszijjarto.com
    url: https://send.skylerszijjarto.com
  - name: send.richy.sh
    url: https://send.richy.sh
  - name: send.majoenell.com
    url: https://send.majoenell.com
  - name: send.blablalinux.be
    url: https://send.blablalinux.be
  - name: send.nog.community
    url: https://send.nog.community

status-website:
  # cname: status.vis.ee
  baseUrl: /send-instances-status
  logoUrl: https://raw.githubusercontent.com/timvisee/send/master/assets/icon.svg
  name: Public Send instances
  introTitle: Public Send service instances
  introMessage: Monitor the status and uptime of the public [Send](https://github.com/timvisee/send) service instances. For more details about each instance, how to use them and how to host your own instance, please see our [Public Send instances](https://github.com/timvisee/send-instances) repository.
  navbar:
    - title: Status
      href: /$REPO
    - title: Send
      href: https://github.com/timvisee/send
    - title: Send instances
      href: https://github.com/timvisee/send-instances
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  favicon: https://raw.githubusercontent.com/timvisee/send/master/assets/favicon-32x32.png
  faviconSvg: https://raw.githubusercontent.com/timvisee/send/master/assets/icon.svg
